/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DatabaseAmazon;

import java.sql.Connection;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sswu
 */
public class UpdateUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUI
     */
    private UpdateDatabase update;
    private String asin;
    private int catId;
    private String catName;
    
    public UpdateUI(Connection mysqlDB) {
        initComponents();
        
        jCatUpdateName.setEditable(false);
        jBelongToId.setEditable(false);
        sTableHeader();
        update = new UpdateDatabase(mysqlDB);
        update.PrepardStatements();
    }
    
    private void sTableHeader() {
        Object[] colCat = new String[]{"ID", "Name"};
        Object[] colProduct = new String[]{"ASIN", "Title", "Salerank", "Type"};
        
        DefaultTableModel modelCat = new DefaultTableModel(0, 0);
        DefaultTableModel modelProduct = new DefaultTableModel(0, 0);
        modelCat.setColumnIdentifiers(colCat);
        modelProduct.setColumnIdentifiers(colProduct);
        jCatTable.setModel(modelCat);
        jProductTable.setModel(modelProduct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCategoryButton = new javax.swing.JButton();
        jCatNameSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCatTable = new javax.swing.JTable();
        jCatInsertButton = new javax.swing.JButton();
        jIdLabel = new javax.swing.JLabel();
        jCatIdInsert = new javax.swing.JTextField();
        jNameLabel = new javax.swing.JLabel();
        jCatNameInsert = new javax.swing.JTextField();
        jDeleteButton = new javax.swing.JButton();
        jCatUpdateButton = new javax.swing.JButton();
        jIdUpdateLabel = new javax.swing.JLabel();
        jCatUpdateId = new javax.swing.JTextField();
        jNameUpdateLabel = new javax.swing.JLabel();
        jCatUpdateName = new javax.swing.JTextField();
        jProductType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jProductTable = new javax.swing.JTable();
        jProductNameLabel = new javax.swing.JLabel();
        jProductName = new javax.swing.JTextField();
        jShowCatButton = new javax.swing.JButton();
        jProductASINLabel = new javax.swing.JLabel();
        jIDlabel = new javax.swing.JLabel();
        jBelongToId = new javax.swing.JTextField();
        jUpdatetBelongToButton = new javax.swing.JButton();
        jAsin = new javax.swing.JTextField();
        jProductASIN = new javax.swing.JLabel();
        jCatIDLabel = new javax.swing.JLabel();
        jBelongToIdInsert = new javax.swing.JTextField();
        jInsertBelongToButton = new javax.swing.JButton();
        jAsinInsert = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCategoryButton.setText("search category by name");
        jCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoryButtonActionPerformed(evt);
            }
        });

        jCatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jCatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCatTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCatTable);

        jCatInsertButton.setText("insert a new category");
        jCatInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCatInsertButtonActionPerformed(evt);
            }
        });

        jIdLabel.setText("ID: ");

        jNameLabel.setText("Name: ");

        jDeleteButton.setText("delete choosing category");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jCatUpdateButton.setText("update an exist category");
        jCatUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCatUpdateButtonActionPerformed(evt);
            }
        });

        jIdUpdateLabel.setText("ID: ");

        jNameUpdateLabel.setText("Name: ");

        jProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "show product list by type", "Book", "DVD", "Music", "Video" }));
        jProductType.setToolTipText("");
        jProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeActionPerformed(evt);
            }
        });

        jProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jProductTable);

        jProductNameLabel.setText("product name: ");

        jShowCatButton.setText("show category");
        jShowCatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowCatButtonActionPerformed(evt);
            }
        });

        jProductASINLabel.setText("Product ASIN: ");

        jIDlabel.setText("Category ID: ");

        jUpdatetBelongToButton.setText("update BelongTo relation");
        jUpdatetBelongToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdatetBelongToButtonActionPerformed(evt);
            }
        });

        jProductASIN.setText("Product ASIN: ");

        jCatIDLabel.setText("Category ID: ");

        jInsertBelongToButton.setText("insert to BelongTo relation");
        jInsertBelongToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBelongToButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jProductASIN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jAsinInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jCatIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBelongToIdInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jInsertBelongToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jProductASINLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jIDlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBelongToId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jUpdatetBelongToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jShowCatButton)
                            .addGap(18, 18, 18)
                            .addComponent(jProductNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jDeleteButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jIdUpdateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCatUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCatIdInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCatNameInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCatInsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNameUpdateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCatUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCatUpdateButton)))
                                .addGap(198, 198, 198))
                            .addComponent(jProductType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCategoryButton)
                            .addGap(18, 18, 18)
                            .addComponent(jCatNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProductName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jShowCatButton)
                        .addComponent(jProductNameLabel)
                        .addComponent(jDeleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCatUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIdUpdateLabel)
                        .addComponent(jCatUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNameUpdateLabel)
                        .addComponent(jCatUpdateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdLabel)
                    .addComponent(jCatIdInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel)
                    .addComponent(jCatNameInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCatInsertButton))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductASINLabel)
                    .addComponent(jAsin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIDlabel)
                    .addComponent(jBelongToId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdatetBelongToButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductASIN)
                    .addComponent(jAsinInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCatIDLabel)
                    .addComponent(jBelongToIdInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInsertBelongToButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCategoryButton)
                    .addComponent(jCatNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setCategoryTable(LinkedList<Category> list) {
        Category c;
        DefaultTableModel model  = (DefaultTableModel)jCatTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < list.size(); ++i) {
            c = list.get(i);
            model.addRow(new Object[]{c.id, c.name});
        }
    }
    
    private void setProductTable(LinkedList<Product> list) {
        Product p;
        DefaultTableModel model = (DefaultTableModel)jProductTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < list.size(); ++i) {
            p = list.get(i);
            model.addRow(new Object[]{p.asin, p.title, p.salerank, p.type});
        }
    }
    
    private void jCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoryButtonActionPerformed
        // TODO add your handling code here:
        String name = jCatNameSearch.getText();
        LinkedList<Category> list = update.searchCatByName(name);
        setCategoryTable(list);
    }//GEN-LAST:event_jCategoryButtonActionPerformed

    private void jProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeActionPerformed
        // TODO add your handling code here:
        String value = jProductType.getSelectedItem().toString();
        if (value.startsWith("Show"))
            return;
        
        LinkedList<Product> list = update.searchProductByType(value);
        setProductTable(list);
        //System.out.println(value);
    }//GEN-LAST:event_jProductTypeActionPerformed

    private void jProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductTableMouseClicked
        // TODO add your handling code here:
        int row = jProductTable.rowAtPoint(evt.getPoint());
        Object objAsin = (Object) jProductTable.getValueAt(row, 0);
        Object objName = (Object) jProductTable.getValueAt(row, 1);
        asin = (String) objAsin;
        jProductName.setText((String)objName);
        jAsin.setText(asin);
    }//GEN-LAST:event_jProductTableMouseClicked

    private void jShowCatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowCatButtonActionPerformed
        // TODO add your handling code here:
        LinkedList<Category> list = update.getCategoryByAsin(asin);
        setCategoryTable(list);
    }//GEN-LAST:event_jShowCatButtonActionPerformed

    private void jCatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCatTableMouseClicked
        // TODO add your handling code here:
        int row = jCatTable.rowAtPoint(evt.getPoint());
        Object objID = (Object) jCatTable.getValueAt(row, 0);
        Object objName = (Object) jCatTable.getValueAt(row, 1);
        catId = (int) objID;
        catName = (String) objName;
        
        jCatUpdateId.setText(String.valueOf(catId));
        jCatUpdateName.setText(catName);
        jBelongToId.setText(String.valueOf(catId));
    }//GEN-LAST:event_jCatTableMouseClicked

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        if (update.deleteCategoryById(catId)) {
            JOptionPane.showMessageDialog(this, "Delete category success!");
        } else {
            JOptionPane.showMessageDialog(this, "Delete category failed");
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jCatInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatInsertButtonActionPerformed
        // TODO add your handling code here:
        int insertId = Integer.parseInt(jCatIdInsert.getText());
        String insertName = jCatNameInsert.getText();
        
        if (update.insertCategory(insertId, insertName)) {
            JOptionPane.showMessageDialog(this, "Insert category success!");
        } else {
            JOptionPane.showMessageDialog(this, "Insert category failed");
        }
    }//GEN-LAST:event_jCatInsertButtonActionPerformed

    private void jInsertBelongToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBelongToButtonActionPerformed
        // TODO add your handling code here:
        int insertId = Integer.parseInt(jBelongToIdInsert.getText());
        String insertAsin = jAsinInsert.getText();
        System.out.println(insertId);
        System.out.println(insertAsin);
        if (update.insertBelongTo(insertAsin, insertId)) {
            JOptionPane.showMessageDialog(this, "Insert belongTo success!");
        } else {
            JOptionPane.showMessageDialog(this, "Insert belongTo failed");
        }
    }//GEN-LAST:event_jInsertBelongToButtonActionPerformed

    private void jCatUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatUpdateButtonActionPerformed
        // TODO add your handling code here:
        int insertId = Integer.parseInt(jCatUpdateId.getText());
        String insertName = jCatUpdateName.getText();
        
        if (update.updateCategory(insertName, insertId)) {
            JOptionPane.showMessageDialog(this, "Update category success!");
        } else {
            JOptionPane.showMessageDialog(this, "Update category failed");
        }
    }//GEN-LAST:event_jCatUpdateButtonActionPerformed

    private void jUpdatetBelongToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdatetBelongToButtonActionPerformed
        // TODO add your handling code here:
        int insertId = Integer.parseInt(jBelongToId.getText());
        String insertAsin = jAsin.getText();
        System.out.println(insertId);
        System.out.println(insertAsin);
        if (update.updateBelongTo(insertAsin, insertId)) {
            JOptionPane.showMessageDialog(this, "Update belongTo success!");
        } else {
            JOptionPane.showMessageDialog(this, "Update belongTo failed");
        }
    }//GEN-LAST:event_jUpdatetBelongToButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UpdateUI().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAsin;
    private javax.swing.JTextField jAsinInsert;
    private javax.swing.JTextField jBelongToId;
    private javax.swing.JTextField jBelongToIdInsert;
    private javax.swing.JLabel jCatIDLabel;
    private javax.swing.JTextField jCatIdInsert;
    private javax.swing.JButton jCatInsertButton;
    private javax.swing.JTextField jCatNameInsert;
    private javax.swing.JTextField jCatNameSearch;
    private javax.swing.JTable jCatTable;
    private javax.swing.JButton jCatUpdateButton;
    private javax.swing.JTextField jCatUpdateId;
    private javax.swing.JTextField jCatUpdateName;
    private javax.swing.JButton jCategoryButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jIDlabel;
    private javax.swing.JLabel jIdLabel;
    private javax.swing.JLabel jIdUpdateLabel;
    private javax.swing.JButton jInsertBelongToButton;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JLabel jNameUpdateLabel;
    private javax.swing.JLabel jProductASIN;
    private javax.swing.JLabel jProductASINLabel;
    private javax.swing.JTextField jProductName;
    private javax.swing.JLabel jProductNameLabel;
    private javax.swing.JTable jProductTable;
    private javax.swing.JComboBox<String> jProductType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jShowCatButton;
    private javax.swing.JButton jUpdatetBelongToButton;
    // End of variables declaration//GEN-END:variables
}
